<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MlM5kW4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mlM5kW4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mlM5kW4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'documentsligne' => ['privates', '.errored..service_locator.mlM5kW4.App\\Entity\\Documentslignes', NULL, 'Cannot autowire service ".service_locator.mlM5kW4": it references class "App\\Entity\\Documentslignes" but no such service exists.'],
        ], [
            'documentsligne' => 'App\\Entity\\Documentslignes',
        ]);
    }
}
