<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5bnQw20Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5bnQw20' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5bnQw20'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'nomenclat' => ['privates', '.errored..service_locator.5bnQw20.App\\Entity\\Numenclat', NULL, 'Cannot autowire service ".service_locator.5bnQw20": it references class "App\\Entity\\Numenclat" but no such service exists.'],
        ], [
            'em' => '?',
            'nomenclat' => 'App\\Entity\\Numenclat',
        ]);
    }
}
