<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Nzt897Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..Nzt897' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..Nzt897'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nomenclat' => ['privates', '.errored..service_locator..Nzt897.App\\Entity\\Numenclat', NULL, 'Cannot autowire service ".service_locator..Nzt897": it references class "App\\Entity\\Numenclat" but no such service exists.'],
        ], [
            'nomenclat' => 'App\\Entity\\Numenclat',
        ]);
    }
}
