<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__8FWVCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..8FW_VC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..8FW_VC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator..8FW_VC.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator..8FW_VC": it references class "App\\Entity\\Articles" but no such service exists.'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Articles',
            'articleRepository' => 'App\\Repository\\ArticlesRepository',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
