<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YJCQvjhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YJCQvjh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YJCQvjh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depot' => ['privates', '.errored..service_locator.YJCQvjh.App\\Entity\\Depots', NULL, 'Cannot autowire service ".service_locator.YJCQvjh": it references class "App\\Entity\\Depots" but no such service exists.'],
            'depotsRepository' => ['privates', 'App\\Repository\\DepotsRepository', 'getDepotsRepositoryService', true],
        ], [
            'depot' => 'App\\Entity\\Depots',
            'depotsRepository' => 'App\\Repository\\DepotsRepository',
        ]);
    }
}
