<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TtVid3IService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ttVid3I' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ttVid3I'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\NomenclatureRepository', 'getNomenclatureRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\NomenclatureRepository',
        ]);
    }
}
