<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kh8CmVlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kh8CmVl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kh8CmVl'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
