<?php

namespace ContainerDart4mh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocuments2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Kel.nqn.App\Entity\Documents' shared service.
     *
     * @return \App\Entity\Documents
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Kel.nqn": it references class "App\\Entity\\Documents" but no such service exists.');
    }
}
