<?php

namespace ContainerOnzFaeV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VAz6QVhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vAz6QVh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vAz6QVh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.vAz6QVh.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.vAz6QVh": it needs an instance of "App\\Entity\\Articles" but this type has been excluded in "config/services.yaml".'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Articles',
            'articleRepository' => 'App\\Repository\\ArticlesRepository',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
