<?php

namespace ContainerOnzFaeV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Esrb5qzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.esrb5qz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.esrb5qz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'function' => ['privates', '.errored..service_locator.esrb5qz.App\\Entity\\Functions', NULL, 'Cannot autowire service ".service_locator.esrb5qz": it needs an instance of "App\\Entity\\Functions" but this type has been excluded in "config/services.yaml".'],
        ], [
            'function' => 'App\\Entity\\Functions',
        ]);
    }
}
