<?php

namespace ContainerOnzFaeV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M6HiOAxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.M6HiOAx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.M6HiOAx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.M6HiOAx.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator.M6HiOAx": it needs an instance of "App\\Entity\\Documents" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'document' => 'App\\Entity\\Documents',
            'entityManager' => '?',
        ]);
    }
}
