<?php

namespace ContainerOnzFaeV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticlesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9VSm2G1.App\Entity\Articles' shared service.
     *
     * @return \App\Entity\Articles
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9VSm2G1": it needs an instance of "App\\Entity\\Articles" but this type has been excluded in "config/services.yaml".');
    }
}
