<?php

namespace ContainerOnzFaeV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocuments2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.b8Xc1kV.App\Entity\Documents' shared service.
     *
     * @return \App\Entity\Documents
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.b8Xc1kV": it needs an instance of "App\\Entity\\Documents" but this type has been excluded in "config/services.yaml".');
    }
}
