<?php

namespace ContainerR8sU2MK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_75zadTAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.75zadTA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.75zadTA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'nomenclat' => ['privates', '.errored..service_locator.75zadTA.App\\Entity\\Nomenclature', NULL, 'Cannot autowire service ".service_locator.75zadTA": it needs an instance of "App\\Entity\\Nomenclature" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'nomenclat' => 'App\\Entity\\Nomenclature',
            'em' => '?',
        ]);
    }
}
