<?php

namespace ContainerR8sU2MK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B8Xc1kVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b8Xc1kV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b8Xc1kV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator.b8Xc1kV.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator.b8Xc1kV": it needs an instance of "App\\Entity\\Documents" but this type has been excluded in "config/services.yaml".'],
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
        ], [
            'document' => 'App\\Entity\\Documents',
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
        ]);
    }
}
