<?php

namespace ContainerR8sU2MK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VvmCTmQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vvmCTmQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vvmCTmQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depot' => ['privates', '.errored..service_locator.vvmCTmQ.App\\Entity\\Depots', NULL, 'Cannot autowire service ".service_locator.vvmCTmQ": it needs an instance of "App\\Entity\\Depots" but this type has been excluded in "config/services.yaml".'],
        ], [
            'depot' => 'App\\Entity\\Depots',
        ]);
    }
}
