<?php

namespace ContainerR8sU2MK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DLwEijJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dLwEijJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dLwEijJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.dLwEijJ.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.dLwEijJ": it needs an instance of "App\\Entity\\Articles" but this type has been excluded in "config/services.yaml".'],
        ], [
            'article' => 'App\\Entity\\Articles',
        ]);
    }
}
