<?php

namespace ContainerR8sU2MK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNomenclatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5Y1U3mZ.App\Entity\Nomenclature' shared service.
     *
     * @return \App\Entity\Nomenclature
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5Y1U3mZ": it needs an instance of "App\\Entity\\Nomenclature" but this type has been excluded in "config/services.yaml".');
    }
}
