<?php

namespace ContainerR8sU2MK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProfilesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XN_Kp_t.App\Entity\Profiles' shared service.
     *
     * @return \App\Entity\Profiles
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XN_Kp_t": it needs an instance of "App\\Entity\\Profiles" but this type has been excluded in "config/services.yaml".');
    }
}
