<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRyxa4rq\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRyxa4rq/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRyxa4rq.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRyxa4rq\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRyxa4rq\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ryxa4rq',
    'container.build_id' => '53b9e2ce',
    'container.build_time' => 1750859746,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRyxa4rq');
