<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container90yWeIv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container90yWeIv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container90yWeIv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container90yWeIv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container90yWeIv\App_KernelDevDebugContainer([
    'container.build_hash' => '90yWeIv',
    'container.build_id' => 'e7586e9e',
    'container.build_time' => 1750773549,
], __DIR__.\DIRECTORY_SEPARATOR.'Container90yWeIv');
