<?php

namespace ContainerRyxa4rq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__UHQe3lService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..UHQe3l' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..UHQe3l'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
        ], [
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
        ]);
    }
}
