<?php

namespace ContainerRyxa4rq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DKJEJmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._dKJEJm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._dKJEJm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'document' => ['privates', '.errored..service_locator._dKJEJm.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator._dKJEJm": it references class "App\\Entity\\Documents" but no such service exists.'],
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
        ], [
            'document' => 'App\\Entity\\Documents',
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
        ]);
    }
}
