<?php

namespace ContainerRyxa4rq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YH2F3dNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yH2F3dN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yH2F3dN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'documentsligne' => ['privates', '.errored..service_locator.yH2F3dN.App\\Entity\\Documentslignes', NULL, 'Cannot autowire service ".service_locator.yH2F3dN": it references class "App\\Entity\\Documentslignes" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'documentsligne' => 'App\\Entity\\Documentslignes',
            'entityManager' => '?',
        ]);
    }
}
