<?php

namespace ContainerRyxa4rq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kel_NqnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Kel.nqn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kel.nqn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'document' => ['privates', '.errored..service_locator.Kel.nqn.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator.Kel.nqn": it references class "App\\Entity\\Documents" but no such service exists.'],
        ], [
            'document' => 'App\\Entity\\Documents',
        ]);
    }
}
