<?php

namespace ContainerRyxa4rq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDocumentslignes2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.yH2F3dN.App\Entity\Documentslignes' shared service.
     *
     * @return \App\Entity\Documentslignes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.yH2F3dN": it references class "App\\Entity\\Documentslignes" but no such service exists.');
    }
}
