<?php

namespace ContainerRyxa4rq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumenclat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5bnQw20.App\Entity\Numenclat' shared service.
     *
     * @return \App\Entity\Numenclat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5bnQw20": it references class "App\\Entity\\Numenclat" but no such service exists.');
    }
}
