<?php

namespace ContainerUKfEepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__MYQtgSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..mYQtgS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..mYQtgS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nomenclature' => ['privates', '.errored..service_locator..mYQtgS.App\\Entity\\Nomenclature', NULL, 'Cannot autowire service ".service_locator..mYQtgS": it references class "App\\Entity\\Nomenclature" but no such service exists.'],
        ], [
            'nomenclature' => 'App\\Entity\\Nomenclature',
        ]);
    }
}
