<?php

namespace ContainerUKfEepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4aR9ZvPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4aR9ZvP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4aR9ZvP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nomenclatureRepository' => ['privates', 'App\\Repository\\NomenclatureRepository', 'getNomenclatureRepositoryService', true],
        ], [
            'nomenclatureRepository' => 'App\\Repository\\NomenclatureRepository',
        ]);
    }
}
