<?php

namespace ContainerUKfEepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O3j4sDoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O3j4sDo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O3j4sDo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nomenclature' => ['privates', '.errored..service_locator.O3j4sDo.App\\Entity\\Nomenclature', NULL, 'Cannot autowire service ".service_locator.O3j4sDo": it references class "App\\Entity\\Nomenclature" but no such service exists.'],
            'nomenclatureRepository' => ['privates', 'App\\Repository\\NomenclatureRepository', 'getNomenclatureRepositoryService', true],
        ], [
            'nomenclature' => 'App\\Entity\\Nomenclature',
            'nomenclatureRepository' => 'App\\Repository\\NomenclatureRepository',
        ]);
    }
}
