<?php

namespace ContainerUKfEepY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNomenclatureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..mYQtgS.App\Entity\Nomenclature' shared service.
     *
     * @return \App\Entity\Nomenclature
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..mYQtgS": it references class "App\\Entity\\Nomenclature" but no such service exists.');
    }
}
