<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articles extends \App\Entity\Articles implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'createAt' => [parent::class, 'createAt', null],
        "\0".parent::class."\0".'createBy' => [parent::class, 'createBy', null],
        "\0".parent::class."\0".'fournisseur' => [parent::class, 'fournisseur', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'reference' => [parent::class, 'reference', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'unite' => [parent::class, 'unite', null],
        'createAt' => [parent::class, 'createAt', null],
        'createBy' => [parent::class, 'createBy', null],
        'fournisseur' => [parent::class, 'fournisseur', null],
        'id' => [parent::class, 'id', null],
        'reference' => [parent::class, 'reference', null],
        'type' => [parent::class, 'type', null],
        'unite' => [parent::class, 'unite', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
