<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Iiufm0nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Iiufm0n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Iiufm0n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'article' => ['privates', '.errored..service_locator.Iiufm0n.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.Iiufm0n": it references class "App\\Entity\\Articles" but no such service exists.'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Articles',
            'articleRepository' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
