<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DxejhxEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dxejhxE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dxejhxE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depot' => ['privates', '.errored..service_locator.dxejhxE.App\\Entity\\Depots', NULL, 'Cannot autowire service ".service_locator.dxejhxE": it references class "App\\Entity\\Depots" but no such service exists.'],
        ], [
            'depot' => 'App\\Entity\\Depots',
        ]);
    }
}
