<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V9gA5PZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v9gA5PZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v9gA5PZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'depotsRepository' => ['privates', 'App\\Repository\\DepotsRepository', 'getDepotsRepositoryService', true],
        ], [
            'depotsRepository' => 'App\\Repository\\DepotsRepository',
        ]);
    }
}
