<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C4_1NiBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C4.1NiB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C4.1NiB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'articlesRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
            'depotsRepository' => ['privates', 'App\\Repository\\DepotsRepository', 'getDepotsRepositoryService', true],
            'stockRepository' => ['privates', 'App\\Repository\\StockRepository', 'getStockRepositoryService', true],
        ], [
            'articlesRepository' => 'App\\Repository\\ArticlesRepository',
            'depotsRepository' => 'App\\Repository\\DepotsRepository',
            'stockRepository' => 'App\\Repository\\StockRepository',
        ]);
    }
}
