<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T97CseEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t97CseE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t97CseE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nomenclature' => ['privates', '.errored..service_locator.t97CseE.App\\Entity\\Numenclat', NULL, 'Cannot autowire service ".service_locator.t97CseE": it references class "App\\Entity\\Numenclat" but no such service exists.'],
        ], [
            'nomenclature' => 'App\\Entity\\Numenclat',
        ]);
    }
}
