<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7zr5f2xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7zr5f2x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7zr5f2x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'nomenclature' => ['privates', '.errored..service_locator.7zr5f2x.App\\Entity\\Numenclat', NULL, 'Cannot autowire service ".service_locator.7zr5f2x": it references class "App\\Entity\\Numenclat" but no such service exists.'],
            'nomenclatureRepository' => ['privates', 'App\\Repository\\NomenclatureRepository', 'getNomenclatureRepositoryService', true],
        ], [
            'nomenclature' => 'App\\Entity\\Numenclat',
            'nomenclatureRepository' => 'App\\Repository\\NomenclatureRepository',
        ]);
    }
}
