<?php

namespace Container90yWeIv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDepotsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YJCQvjh.App\Entity\Depots' shared service.
     *
     * @return \App\Entity\Depots
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YJCQvjh": it references class "App\\Entity\\Depots" but no such service exists.');
    }
}
