<?php

namespace ContainerCph9b7n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9VSm2G1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9VSm2G1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9VSm2G1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.9VSm2G1.App\\Entity\\Articles', NULL, 'Cannot autowire service ".service_locator.9VSm2G1": it needs an instance of "App\\Entity\\Articles" but this type has been excluded in "config/services.yaml".'],
            'articleRepository' => ['privates', 'App\\Repository\\ArticlesRepository', 'getArticlesRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Articles',
            'articleRepository' => 'App\\Repository\\ArticlesRepository',
        ]);
    }
}
