<?php

namespace ContainerCph9b7n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XNKpTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XN_Kp_t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XN_Kp_t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'profile' => ['privates', '.errored..service_locator.XN_Kp_t.App\\Entity\\Profiles', NULL, 'Cannot autowire service ".service_locator.XN_Kp_t": it needs an instance of "App\\Entity\\Profiles" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'profile' => 'App\\Entity\\Profiles',
            'entityManager' => '?',
        ]);
    }
}
