<?php

namespace ContainerCph9b7n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KmEPCuRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kmEPCuR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kmEPCuR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
        ], [
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
        ]);
    }
}
