<?php

namespace ContainerCph9b7n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BYcHeuAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bYcHeuA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bYcHeuA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'depot' => ['privates', '.errored..service_locator.bYcHeuA.App\\Entity\\Depots', NULL, 'Cannot autowire service ".service_locator.bYcHeuA": it needs an instance of "App\\Entity\\Depots" but this type has been excluded in "config/services.yaml".'],
            'depotsRepository' => ['privates', 'App\\Repository\\DepotsRepository', 'getDepotsRepositoryService', true],
        ], [
            'depot' => 'App\\Entity\\Depots',
            'depotsRepository' => 'App\\Repository\\DepotsRepository',
        ]);
    }
}
