<?php

namespace ContainerCph9b7n;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFunctions2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fDHkg96.App\Entity\Functions' shared service.
     *
     * @return \App\Entity\Functions
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fDHkg96": it needs an instance of "App\\Entity\\Functions" but this type has been excluded in "config/services.yaml".');
    }
}
