<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOnzFaeV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOnzFaeV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOnzFaeV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOnzFaeV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOnzFaeV\App_KernelDevDebugContainer([
    'container.build_hash' => 'OnzFaeV',
    'container.build_id' => '7f8f0a2c',
    'container.build_time' => 1751888363,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOnzFaeV');
