<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXRhSbF7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXRhSbF7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXRhSbF7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXRhSbF7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXRhSbF7\App_KernelDevDebugContainer([
    'container.build_hash' => 'XRhSbF7',
    'container.build_id' => 'd016f270',
    'container.build_time' => 1752761830,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXRhSbF7');
