<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articles extends \App\Entity\Articles implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'fournisseur', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'unite', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'createBy', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'createAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'reference', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'fournisseur', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'unite', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'createBy', '' . "\0" . 'App\\Entity\\Articles' . "\0" . 'createAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Articles $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId(int $id): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference(string $reference): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$reference]);

        return parent::setReference($reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getFournisseur(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFournisseur', []);

        return parent::getFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFournisseur(?\App\Entity\Users $fournisseur): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFournisseur', [$fournisseur]);

        return parent::setFournisseur($fournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnite(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnite', []);

        return parent::getUnite();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnite(string $unite): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnite', [$unite]);

        return parent::setUnite($unite);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateBy(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateBy', []);

        return parent::getCreateBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateBy(?\App\Entity\Users $createBy): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateBy', [$createBy]);

        return parent::setCreateBy($createBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateAt', []);

        return parent::getCreateAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateAt(\DateTimeInterface $createAt): \App\Entity\Articles
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateAt', [$createAt]);

        return parent::setCreateAt($createAt);
    }

}
